export const colorScheme = {
  primary: "#F5E7ED",
  secondary: "#BABCC0",
  accent: "#F0D69A",
  accentText: "#755A1A",
  background: "#FCF7F9",
  foreground: "#2B2428",
  foregroundLight: "#FFF9FB",
  muted: "#665B61",
  surface: "#FFFDFE",
  surfaceWarm: "#F9EEF3",
  primaryContrast: "#2B2428",
  secondaryContrast: "#25272A",
  accentContrast: "#2F2613",
  heroOverlay: "#150F12",
  shadowSoft: "rgb(43 36 40 / 8%)",
  shadowSubtle: "rgb(43 36 40 / 6%)",
  borderStrong: "rgb(43 36 40 / 16%)",
  glowSoft: "rgb(240 214 154 / 20%)",
  glowStrong: "rgb(240 214 154 / 62%)",
  glowHalo: "rgb(240 214 154 / 28%)",
} as const;

export const themeCssVariables = {
  "--primary": colorScheme.primary,
  "--secondary": colorScheme.secondary,
  "--accent": colorScheme.accent,
  "--accent-text": colorScheme.accentText,
  "--background": colorScheme.background,
  "--foreground": colorScheme.foreground,
  "--foreground-light": colorScheme.foregroundLight,
  "--muted": colorScheme.muted,
  "--surface": colorScheme.surface,
  "--surface-warm": colorScheme.surfaceWarm,
  "--primary-contrast": colorScheme.primaryContrast,
  "--secondary-contrast": colorScheme.secondaryContrast,
  "--accent-contrast": colorScheme.accentContrast,
  "--hero-overlay": colorScheme.heroOverlay,
  "--shadow-soft": colorScheme.shadowSoft,
  "--shadow-subtle": colorScheme.shadowSubtle,
  "--border-strong": colorScheme.borderStrong,
  "--glow-soft": colorScheme.glowSoft,
  "--glow-strong": colorScheme.glowStrong,
  "--glow-halo": colorScheme.glowHalo,
} as const;
